### ISSUE TITLE
emulator .z80 snapshot

### ISSUE THREAD

**Issue by folkertvanheusden** [redcode/Z80_XCF_Flavor#1]
Hi,

Please consider releasing this software as an emulator snapshot (.z80-file) as well as .tap is kind of difficult to emulate.

**Comment by redcode** [comment]
Unfortunately, SjASMPlus can't generate snapshots in Z80 format, but I've added the generation of a SNA snapshot, which is simpler format.

https://github.com/redcode/Z80_XCF_Flavor/releases/tag/v1.3

**Comment by redcode** [comment]
Unfortunately, SjASMPlus can't generate snapshots in Z80 format, but I've added the generation of a SNA snapshot, which is a simpler format.

https://github.com/redcode/Z80_XCF_Flavor/releases/tag/v1.3

**Comment by folkertvanheusden** [comment]
Thanks!
